-- MySQL / MariaDB
CREATE TABLE IF NOT EXISTS property_images (
  id          VARCHAR(64) PRIMARY KEY,
  property_id VARCHAR(64) NOT NULL,
  image_url   VARCHAR(512) NOT NULL,
  image_path  VARCHAR(512) NOT NULL,
  is_main     TINYINT(1) NOT NULL DEFAULT 0,
  sort_order  INT DEFAULT 0,
  created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_property (property_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;